services:
  server:
    build: .
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
  nginx:
    image: "nginx:latest"
    ports:
      - 80:1231
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
      POSTGRES_DB: db
    ports:
      - 5432:5432
