services:
  server:
    build: .
    container_name: server
    # ports:
    #   - 8080:8080
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1231:80
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
      POSTGRES_DB: db
    ports:
      - 5432:5432
